version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - "16543:80"
    networks:
      - postgres

    postgres-mcp:
    build: ./postgres-mcp
    restart: always
    ports:
      - "8888:8080"  
    env_file: .env
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
