version: "3.8"

services:
  postgres-mcp:
    build: ./postgres-mcp
    restart: always
    ports:
      - "8888:8080"
    env_file: .env
    networks:
      - postgres

networks:
  postgres:
    external: true
